kind: pipeline
name: default
type: kubernetes

steps:
  - name: docker build & push
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      registry: git.datti.to
      repo: git.datti.to/dattito/timetable-dhbw
      username:
        from_secret: GIT_USER
      password:
        from_secret: GIT_PASSWORD
      tags: latest
      platforms: [linux/amd64, linux/arm64]
